services:

  postgres:
    image: postgres:15
    container_name: booking-postgres
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    container_name: booking-redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: booking-app
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8080:8080"
    restart: always